[project]
name = "bayesianml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.5.1",
    "numpy>=2.2.3",
    "seaborn>=0.13.2",
]
